2024-10-28 23:13:49,738 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\URBAN\pythonProject12\tests_12_4.py", line 24, in test_run
    object_2 = runner.Runner(67, 5)
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\URBAN\pythonProject12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-28 23:13:49,740 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\URBAN\pythonProject12\tests_12_4.py", line 12, in test_walk
    object_1 = runner.Runner('Vanya', -10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\URBAN\pythonProject12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
